### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by robertvandeneynde** [robertvandeneynde/sierra#1]
~{"deadline": "Sat 27 Oct 2018 23h"}~
~{"deadline": "Sat 3 Nov 2018 23h"}~

# Misc
- [x] Setup sierra.robertvandeneynde.be (user: phys-opera)
- [ ] Find the Service de calcul to have our own opera server accessible via ssh
- [x] 2018-2019 uses current year instead of academic year #bug
- [ ] access to subject.pdf only for people with Read permission

# QR code
- [x] Latex: find module that can print QR code in 1in×1in at top right of page
- [x] Content of QRCode: `v1/acadyear/epreuve/serie/page` (like `2017-2018/ExamJuin/a`)
- [x] Content of QRCode: `v1.1/mnemo/acadyear/epreuve/serie/papernumber/page` (like `PHYSH101/2017-2018/ExamJuin/a/199/3`)
- [ ] Sierra read QRCode and prompt the user if the directory is understood correctly

# Login
- [ ] Create a login with roles : Readonly, ReadWrite
- [ ] Roles Types: Assistant, Prof (Student(Matricule, Nom, Prenom, netid, email:ulb))

# Create project (exam-prepare)
- [x] Upload latex file
- [ ] Some files are included
  - amc style (.sty) by robin included, containing useful macros
  - defquestions.sty

# Scans
- [ ] One can upload if have write permisison
- [ ] Understand the bash command to put files in a project (AMC-analyse), --seuil-coche, beware of --ignore-red

# Correction status
- [ ] Can deduce from scan state which correction is to be done
- [ ] Create Corrector Policy, PerQuestionCorrector: Each question has a corrector

# Page "project"
- [ ] Ajouter des images/pdf/dépendances pour la compilation
- [ ] When we upload a source that doesn't compile, remove subject.pdf (so that `does_compile==False`)
- [ ] Ajouter une liste des scans importés et le nombre de scans (en bas de la liste)

# Ideas
- SierraSearchFilter: space means `and`
- Simple versioning for .tex _project_ (think, git)
- Css: ProjectPage: Upload source.tex should be a dropzone box.
- Click on _Sierra_ clears and focus search input
- Click on section like Lecture toggles visibility
- Toggles information for each _action_ (like _if you have ssh access_ on _Import a project_)

# Bugs
- Search for a should not give that ![screenshot_2018-11-02_03 02_27](https://user-images.githubusercontent.com/7661856/47889746-c5f6cf00-de4b-11e8-8aaa-8b8742818ea9.png)
